### ISSUE TITLE
An error when compile the software

### ISSUE THREAD

**Issue by sillycheng** [abelcarreras/symgroup#1]
I want to calculate the CSM of different molecules, so this software is very helpful for me. However, there is an error when I compile this software. When I enter "make" command, there will be error like this
`
CMakeFiles/symgroup.dir/src/operations.F.o: In function `iternewton_':
operations.F:(.text+0x2e1): undefined reference to `dgesv_'
collect2: error: ld returned 1 exit status
CMakeFiles/symgroup.dir/build.make:302: recipe for target '../EXE/symgroup' failed
make[2]: *** [../EXE/symgroup] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/symgroup.dir/all' failed
make[1]: *** [CMakeFiles/symgroup.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`
I want to know how to fix this error, or can you send me an pre-compile version of this software?

**Comment by abelcarreras** [comment]
Looks like a problem with LAPACK library.
Do you have LAPACK/BLAS libraries properly installed in your system?
Which OS, compiler & Lapack library are you using?

**Comment by sillycheng** [comment]
> Looks like a problem with LAPACK library.
> Do you have LAPACK/BLAS libraries properly installed in your system?
> Which OS, compiler & Lapack library are you using?

I test it on Ubuntu 18.04.2. And I have installed LAPACK 3.9.0 and BLAS 3.8.0 libraries. The cmake version is 3.10.2, and the compiler is fort77.

**Comment by sillycheng** [comment]
> Looks like a problem with LAPACK library.
> Do you have LAPACK/BLAS libraries properly installed in your system?
> Which OS, compiler & Lapack library are you using?

**Comment by abelcarreras** [comment]
I have never used fort77 to compile this software,
I tested with intel fortran and gfortran and it compiles well.
can you try using gfortran compiler?

If you check the travis.yaml you will see the packages that you need to compile symgroup on a clean ubuntu machine:

- sudo apt-get install libblas-dev liblapack-dev
- sudo apt-get install gfortran

**Comment by abelcarreras** [comment]
In any case, symgroup code structure is very simple. 
If cmake does not work, you can always just compile the source files listed in CmakeList.txt directly

"src/symgroup.F"
 "src/radius.F"
"src/connectivity.F"
 "src/jacobi.F"
 "src/linear_algebra.F"
"src/mass.F"
 "src/measure.F"
 "src/operations.F"
 "src/read_input.F"

linking them with Lapack and Blas libraries (-llapack -lblas)
to get the binary.

If no luck, yes, I can send you a compiled binary for ubuntu.

**Comment by sillycheng** [comment]
> I have never used fort77 to compile this software,
> I tested with intel fortran and gfortran and it compiles well.
> can you try using gfortran compiler?
> 
> If you check the travis.yaml you will see the packages that you need to compile symgroup on a clean ubuntu machine:
> 
> * sudo apt-get install libblas-dev liblapack-dev
> * sudo apt-get install gfortran

It success when I compile it on another computer, thank you for your help.

I have another question, my research need to measure the chirality of organic molecules, how can I use symgroup to get it with python API?

**Comment by abelcarreras** [comment]
For chirality measurement you can use symmetry measure (CSM) of group CS (which only contains Identity and reflection operations). To use Pyhon API check README file simple example. Something like this:

```python
from symgroupy import Symgroupy

fen4 = Symgroupy(coordinates=[[15.5182, -1.68040, 22.81703],
                                      [6.78978, -3.22298, 23.08474],
                                      [6.27712, -0.12712, 21.76775],
                                      [4.24692, -3.22298, 22.54931],
                                      [4.75958, -0.12712, 23.86630]],
                 group='Cs',
                 labels=['Fe', 'N', 'N', 'N', 'N'],
                 central_atom=1)

print('Chirality: {}'.format(fen4.csm))
```

**Comment by sillycheng** [comment]
> For chirality measurement you can use symmetry measure (CSM) of group CS (which only contains Identity and reflection operations). To use Pyhon API check README file simple example. Something like this:
> 
> ```python
> from symgroupy import Symgroupy
> 
> fen4 = Symgroupy(coordinates=[[15.5182, -1.68040, 22.81703],
>                                       [6.78978, -3.22298, 23.08474],
>                                       [6.27712, -0.12712, 21.76775],
>                                       [4.24692, -3.22298, 22.54931],
>                                       [4.75958, -0.12712, 23.86630]],
>                  group='Cs',
>                  labels=['Fe', 'N', 'N', 'N', 'N'],
>                  central_atom=1)
> 
> print('Chirality: {}'.format(fen4.csm))
> ```

Thank you very much!
